services:
    svelte-hack-api:
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes:
            - ./pb_data:/app/pb_data
        restart: always
        network_mode: host
